Preventing errors with LVM when re-running the playbook
elastic/ansible-elastic-cloud-enterprise pull request #116
Opened 2021-03-15 19:39 UTC by ugosan

This PR solves issues with LVM when re-running the playbook after a failed run, when external disk is already formatted and swap partition is already created:

```
TASK [ansible-elastic-cloud-enterprise : Create data volume] ***************************************************************
fatal: [host1]: FAILED! => {"changed": false, "msg": "Sorry, no shrinking of data to 0 permitted."}
```

```
TASK [ansible-elastic-cloud-enterprise : Setup swap] ***********************************************************************
fatal: [host1]: FAILED! => {"changed": true, "cmd": ["mkswap", "/dev/lxc/swap"], "delta": "0:00:00.004355", "end": "2021-03-15 17:57:19.994434", "msg": "non-zero return code", "rc": 1, "start": "2021-03-15 17:57:19.990079", "stderr": "mkswap: error: /dev/lxc/swap is mounted; will not make swapspace", "stderr_lines": ["mkswap: error: /dev/lxc/swap is mounted; will not make swapspace"], "stdout": "", "stdout_lines": []}
```

2021-03-15 20:02 UTC, ugosan commented
Just tested with a fresh install and with a interrupted previous installation, both work fine

2021-03-15 22:00 UTC, rhass requested changes
I am a 👎  on this change. It seems the problem is [the swap creation step isn't idempotent](https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/6f415b0f07d37ab967538b930477022c1194b094/tasks/direct-install/setup_xfs.yml#L32). Instead of unmounting the swap partition, we should just check to see if we need to create it before attempting to do so.

2021-03-15 22:04 UTC, rhass commented
It looks like the filesystem module supports the `fstype` of `swap`: 

https://docs.ansible.com/ansible/latest/collections/community/general/filesystem_module.html

2021-03-16 00:22 UTC, ugosan commented
@rhass Fair enough, I've changed the swap creation to use the filesystem module:
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/17125/111237555-52d8f800-85c3-11eb-90fc-ed96a6ab1503.png">

2021-03-16 00:22 UTC, rhass approved these changes

2021-03-16 13:44 UTC, merged

2021-03-16 18:44 UTC, obierlaire commented
Our CI seems happy with it. Thanks @ugosan, great to have this improvement!